export const CHARACTERS_FETCH_SUCCEEDED = 'CHARACTERS_FETCH_SUCCEEDED';
export const SELECTED_CHARACTER_FETCH_SUCCEEDED = 'SELECTED_CHARACTER_FETCH_SUCCEEDED';
export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_SELECTED_CHARACTER = 'GET_SELECTED_CHARACTER';
export const SEARCH_CHARACTERS = 'SEARCH_CHARACTERS';
export const CHARACTERS_SEARCH_SUCCEEDED = 'CHARACTERS_SEARCH_SUCCEEDED';

