export const COMICS_FETCH_SUCCEEDED = 'COMICS_FETCH_SUCCEEDED';
export const SELECTED_COMIC_FETCH_SUCCEEDED = 'SELECTED_COMIC_FETCH_SUCCEEDED';
export const GET_COMICS = 'GET_COMICS';
export const GET_SELECTED_COMIC = 'GET_SELECTED_COMIC';
