export const COMICS_FETCH_SUCCEEDED = 'COMICS_FETCH_SUCCEEDED';
export const SELECTED_COMIC_FETCH_SUCCEEDED = 'SELECTED_COMIC_FETCH_SUCCEEDED';
export const GET_COMICS = 'GET_COMICS';
export const GET_SELECTED_COMIC = 'GET_SELECTED_COMIC';
export const SEARCH_COMICS = 'SEARCH_COMICS';
export const SEARCH_COMICS_BY_LETTER = 'SEARCH_COMICS_BY_LETTER';
export const COMICS_SEARCH_SUCCEEDED = 'COMICS_SEARCH_SUCCEEDED';
