export const CREATORS_FETCH_SUCCEEDED = 'CREATORS_FETCH_SUCCEEDED';
export const SELECTED_CREATOR_FETCH_SUCCEEDED = 'SELECTED_CREATOR_FETCH_SUCCEEDED';
export const GET_CREATORS = 'GET_CREATORS';
export const GET_SELECTED_CREATOR = 'GET_SELECTED_CREATOR';
