export const LOADING = 'LOADING';
export const FETCH_FAILED = 'FETCH_FAILED';
export const SET_APPLICATION_ERROR = 'SET_APPLICATION_ERROR';
export const CLEAR_API_ERRORS = 'CLEAR_API_ERRORS';
export const SHOW_FLASH_MESSAGE = 'SHOW_FLASH_MESSAGE';
export const HIDE_FLASH_MESSAGE = 'HIDE_FLASH_MESSAGE';
export const SHOW_SAVE_ITEM_ERROR_MODAL = 'SHOW_SAVE_ITEM_ERROR_MODAL';
export const HIDE_SAVE_ITEM_ERROR_MODAL = 'HIDE_SAVE_ITEM_ERROR_MODAL';
export const HIDE_SERVER_ERROR_MODAL = 'HIDE_SERVER_ERROR_MODAL';
export const SET_PAGINATION_DATA = 'SET_PAGINATION_DATA';

