export const EVENTS_FETCH_SUCCEEDED = 'EVENTS_FETCH_SUCCEEDED';
export const SELECTED_EVENT_FETCH_SUCCEEDED = 'SELECTED_EVENT_FETCH_SUCCEEDED';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_SELECTED_EVENT = 'GET_SELECTED_EVENT';
