export const SERIES_FETCH_SUCCEEDED = 'SERIES_FETCH_SUCCEEDED';
export const SELECTED_SERIES_FETCH_SUCCEEDED = 'SELECTED_SERIES_FETCH_SUCCEEDED';
export const GET_SERIES = 'GET_SERIES';
export const GET_SELECTED_SERIES = 'GET_SELECTED_SERIES';
