export const REGISTRATION_ATTEMPT = 'REGISTRATION_ATTEMPT';
export const REGISTRATION_SUCCEEDED = 'REGISTRATION_SUCCEEDED';
export const GET_USER = 'GET USER';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
